import type {
  MeasurementProfileData,
  AppointmentSlotData,
  AppointmentRequestData,
  BespokeRequestData,
} from "./types";

export const DEMO_MEASUREMENT_PROFILES: MeasurementProfileData[] = [
  {
    id: "mp-1",
    userId: "usr-1",
    name: "Bridal Fit '26",
    isDefault: true,
    unit: "inches",
    height: 67,
    chest: 36,
    waist: 28,
    hip: 39,
    shoulder: 15.5,
    sleeve: 23,
    inseam: 31,
    neck: 13.5,
    notes: "Fitted waist preference for corset lehenga.",
    createdAt: "2026-07-20T10:00:00.000Z",
  },
  {
    id: "mp-2",
    userId: "usr-1",
    name: "Winter Gala Suit",
    isDefault: false,
    unit: "inches",
    height: 67,
    chest: 37,
    waist: 29,
    hip: 40,
    shoulder: 16,
    sleeve: 23.5,
    inseam: 31,
    neck: 14,
    notes: "Relaxed fit for layered cashmere velvet.",
    createdAt: "2026-07-22T10:00:00.000Z",
  },
];

export const DEMO_APPOINTMENT_SLOTS: AppointmentSlotData[] = [
  {
    id: "slot-1",
    designerId: "dh-1",
    designerName: "MAISON RIVIÈRE",
    date: "2026-08-05",
    startTime: "11:00",
    endTime: "12:00",
    type: "virtual",
    isAvailable: true,
  },
  {
    id: "slot-2",
    designerId: "dh-1",
    designerName: "MAISON RIVIÈRE",
    date: "2026-08-05",
    startTime: "14:00",
    endTime: "15:00",
    type: "studio_visit",
    isAvailable: true,
  },
  {
    id: "slot-3",
    designerId: "dh-2",
    designerName: "KISHANGARH",
    date: "2026-08-06",
    startTime: "16:00",
    endTime: "17:00",
    type: "phone",
    isAvailable: true,
  },
];

export const DEMO_APPOINTMENT_REQUESTS: AppointmentRequestData[] = [
  {
    id: "app-1",
    userId: "usr-1",
    userName: "Aria Dev",
    designerId: "dh-1",
    designerName: "MAISON RIVIÈRE",
    slotId: "slot-1",
    preferredDate: "2026-08-05",
    preferredTime: "11:00 AM",
    appointmentType: "virtual",
    purpose: "Bridal Lehenga Consultation",
    message: "Discussing zardozi border customizations and corset fitting.",
    status: "confirmed",
    statusNotes: "Confirmed via Maison Atelier Concierge.",
    createdAt: "2026-07-29T10:00:00.000Z",
  },
];

export const DEMO_BESPOKE_REQUESTS: BespokeRequestData[] = [
  {
    id: "bespoke-1",
    userId: "usr-1",
    userName: "Aria Dev",
    designerId: "dh-1",
    designerName: "MAISON RIVIÈRE",
    productId: "prod-1",
    productName: "Zardozi Velvet Lehenga",
    category: "Bridal Lehenga",
    occasion: "Reception Gala",
    budget: 350000,
    deadline: "2026-10-15",
    notes: "Deep royal indigo velvet with antique gold bullion zardozi embroidery.",
    statusNotes: "Master weaver assigned at Mumbai atelier.",
    measurementProfileId: "mp-1",
    measurements: {
      chest: 36,
      waist: 28,
      hip: 39,
      shoulder: 15.5,
    },
    referenceImages: [
      "https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=800&q=80",
    ],
    attachments: [
      {
        id: "att-1",
        requestId: "bespoke-1",
        url: "https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=800&q=80",
        title: "Moodboard Reference",
        type: "inspiration_image",
        createdAt: "2026-07-29T11:00:00.000Z",
      },
      {
        id: "att-2",
        requestId: "bespoke-1",
        url: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=800&q=80",
        title: "Embroidery Swatch Sketch",
        type: "sketch",
        createdAt: "2026-07-29T11:05:00.000Z",
      },
    ],
    messages: [
      {
        id: "msg-1",
        requestId: "bespoke-1",
        senderId: "usr-1",
        senderRole: "buyer",
        senderName: "Aria Dev",
        message: "Can we replace silver zari with 24k antique gold bullion thread?",
        createdAt: "2026-07-29T11:10:00.000Z",
      },
      {
        id: "msg-2",
        requestId: "bespoke-1",
        senderId: "des-1",
        senderRole: "designer",
        senderName: "Maison Master Weaver",
        message: "Absolutely! We will weave the swatch sample this week and upload a photo for review.",
        createdAt: "2026-07-29T12:30:00.000Z",
      },
    ],
    status: "in_production",
    createdAt: "2026-07-29T10:30:00.000Z",
    updatedAt: "2026-07-30T14:00:00.000Z",
  },
];
